# Generated by Django 4.2.7 on 2025-07-06 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('eta_minutes', models.IntegerField(default=30)),
                ('robot_id', models.CharField(blank=True, max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
